-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.33-0ubuntu0.14.04.1 - (Ubuntu)
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for stockTrader
CREATE DATABASE IF NOT EXISTS `stockTrader` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `stockTrader`;

-- Dumping structure for table stockTrader.config
CREATE TABLE IF NOT EXISTS `config` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `keyVal` varchar(255) DEFAULT NULL,
  `valueVal` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical
CREATE TABLE IF NOT EXISTS `historical` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `status` varchar(11) DEFAULT NULL,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` varchar(100) DEFAULT '',
  `uuid` varchar(80) DEFAULT NULL,
  `success` varchar(15) DEFAULT NULL,
  `message` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=19234375 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_archive
CREATE TABLE IF NOT EXISTS `historical_archive` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `status` varchar(11) DEFAULT NULL,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` varchar(100) DEFAULT '',
  `uuid` varchar(80) DEFAULT NULL,
  `success` varchar(15) DEFAULT NULL,
  `message` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=19009137 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test
CREATE TABLE IF NOT EXISTS `historical_test` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_backup
CREATE TABLE IF NOT EXISTS `historical_test_backup` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcbay
CREATE TABLE IF NOT EXISTS `historical_test_btcbay` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  `status` varchar(20) DEFAULT NULL,
  `uuid` varchar(80) DEFAULT NULL,
  `message` varchar(250) DEFAULT NULL,
  `success` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=65014 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcdash
CREATE TABLE IF NOT EXISTS `historical_test_btcdash` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=115431 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcgno
CREATE TABLE IF NOT EXISTS `historical_test_btcgno` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  `status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=470433 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcmco
CREATE TABLE IF NOT EXISTS `historical_test_btcmco` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58107 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcnav
CREATE TABLE IF NOT EXISTS `historical_test_btcnav` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcnxt
CREATE TABLE IF NOT EXISTS `historical_test_btcnxt` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  `status` varchar(20) DEFAULT NULL,
  `uuid` varchar(80) DEFAULT NULL,
  `message` varchar(250) DEFAULT NULL,
  `success` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62697 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcsc
CREATE TABLE IF NOT EXISTS `historical_test_btcsc` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` text,
  `status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=194637 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.historical_test_btcxem
CREATE TABLE IF NOT EXISTS `historical_test_btcxem` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `status` varchar(11) DEFAULT NULL,
  `MarketName` varchar(30) DEFAULT '',
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) unsigned zerofill DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `_id` varchar(50) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `logicGate3` tinyint(1) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(500) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `debug` varchar(100) DEFAULT '',
  `uuid` varchar(80) DEFAULT NULL,
  `success` varchar(15) DEFAULT NULL,
  `message` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MarketName` (`MarketName`),
  KEY `unixTime` (`unixTime`),
  KEY `_id` (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2148741 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.positions
CREATE TABLE IF NOT EXISTS `positions` (
  `type` varchar(50) DEFAULT NULL,
  `status` varchar(11) DEFAULT NULL,
  `maxPrice` decimal(20,10) DEFAULT NULL,
  `buyPrice` decimal(20,10) DEFAULT NULL,
  `MarketName` varchar(30) DEFAULT '',
  `amountOfCurrency` decimal(20,10) DEFAULT NULL,
  `costInBtc` decimal(20,10) DEFAULT NULL,
  `averagePrice` decimal(20,10) DEFAULT NULL,
  `sellPrice` decimal(20,10) DEFAULT NULL,
  `Last` decimal(20,10) DEFAULT NULL,
  `amountSpent` decimal(20,10) DEFAULT NULL,
  `currentBuyAllocationAccountValueBtc` decimal(20,10) DEFAULT NULL,
  `timeEntered` varchar(50) DEFAULT NULL,
  `unixTime` int(32) DEFAULT NULL,
  `High` decimal(20,10) DEFAULT NULL,
  `Low` decimal(20,10) DEFAULT NULL,
  `Volume` decimal(20,10) DEFAULT NULL,
  `BaseVolume` decimal(20,10) DEFAULT NULL,
  `TimeStamp` varchar(50) DEFAULT NULL,
  `Bid` decimal(20,10) DEFAULT NULL,
  `Ask` decimal(20,10) DEFAULT NULL,
  `OpenBuyOrders` double(20,1) DEFAULT NULL,
  `OpenSellOrders` decimal(20,1) DEFAULT NULL,
  `PrevDay` decimal(20,10) DEFAULT NULL,
  `Created` varchar(50) DEFAULT NULL,
  `_id` varchar(60) DEFAULT NULL,
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `debug` varchar(255) DEFAULT '',
  `averageVolume` decimal(20,10) DEFAULT NULL,
  `averagePriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `averageVolumeLastNTicks` decimal(20,10) DEFAULT NULL,
  `longerPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `shortPriceLastNTicks` decimal(20,10) DEFAULT NULL,
  `technicalAverage` decimal(20,10) DEFAULT NULL,
  `logicGate1` tinyint(1) DEFAULT NULL,
  `logicGate2` tinyint(1) DEFAULT NULL,
  `message` varchar(200) DEFAULT NULL,
  `success` varchar(15) DEFAULT '',
  `logicGate3` tinyint(1) DEFAULT NULL,
  `uuid` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MEMORY AUTO_INCREMENT=1582 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.saved
CREATE TABLE IF NOT EXISTS `saved` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `keya` varchar(255) DEFAULT NULL,
  `valuea` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
-- Dumping structure for table stockTrader.test
CREATE TABLE IF NOT EXISTS `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
